baseURL = 'https://alexandreroman.fr/'
languageCode = 'en'
title = 'Alexandre Roman'
theme = []

[params]
  description = "Personal landing page of Alexandre Roman. Pre-Sales Expert (Solution Engineer) specializing in Cloud Native technologies, Java, and AI."

[params.social]
  github = "https://aro.fyi/github"
  linkedin = "https://aro.fyi/linkedin"
  x = "https://aro.fyi/x"
  bluesky = "https://aro.fyi/bluesky"
  cv = "https://docs.google.com/document/d/1wZiPzqXPqe6OFQ3ePYIL1QytDv5yRWfOZhfIZNE8j04/edit?usp=sharing"
